### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by vinsuz** [gregjhogan/redirect-http-to-https-site-extension#2]
I installed the extension on two apps and the redirect is not working. PM me for a sample url.

**Comment by gregjhogan** [comment]
Sounds similar to #1.  Did you restart the site?   applicationHost.xdt changes are only picked up on restart: https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#private-extensions

**Comment by vinsuz** [comment]
Sorry, I didn't see Issue #1 (since it was closed?), and I SWEAR I stopped and started **both** apps -- I have other extensions installed, so I know not to trust the 'Restart' button. Of course, going back in and stopping/starting them again did the trick.

Thanks for the extension Greg!
