### ISSUE TITLE
Remove the extension

### ISSUE THREAD

**Issue by mnecci** [gregjhogan/redirect-http-to-https-site-extension#6]
Hi,
I tried to remove the extension, but traffic continues to be redirected to HTTPS.
How can I bring the situation back to its original state?

Best regards

**Comment by NightWuYo** [comment]
I met the same problem, please help.
For why I remove the extension: it breaks my web api(s) in the same site.

**Comment by NightWuYo** [comment]
Just found a solution:
Re-deploy the service.

**Comment by gregjhogan** [comment]
It uses a permanent redirect, so you may have to restart the site and your browser, too.  There is nothing I can do about this, so closing.  Thanks!
